export const categoryTranslations = {
  "General Knowledge": "Conocimientos Generales",
  "Entertainment: Books": "Entretenimiento: Libros",
  "Entertainment: Film": "Entretenimiento: Películas",
  "Entertainment: Music": "Entretenimiento: Música",
  "Entertainment: Musicals & Theatres": "Entretenimiento: Musicales y Teatro",
  "Entertainment: Television": "Entretenimiento: Televisión",
  "Entertainment: Video Games": "Entretenimiento: Videojuegos",
  "Entertainment: Board Games": "Entretenimiento: Juegos de Mesa",
  "Science & Nature": "Ciencia y Naturaleza",
  "Science: Computers": "Ciencia: Computadoras",
  "Science: Mathematics": "Ciencia: Matemáticas",
  "Mythology": "Mitología",
  "Sports": "Deportes",
  "Geography": "Geografía",
  "History": "Historia",
  "Politics": "Política",
  "Art": "Arte",
  "Celebrities": "Celebridades",
  "Animals": "Animales",
  "Vehicles": "Vehículos",
  "Entertainment: Comics": "Entretenimiento: Cómics",
  "Science: Gadgets": "Ciencia: Gadgets",
  "Entertainment: Japanese Anime & Manga": "Entretenimiento: Anime y Manga Japonés",
  "Entertainment: Cartoon & Animations": "Entretenimiento: Dibujos y Animaciones",
};
