export const categoryTranslations = {
  "General Knowledge": "Conhecimentos Gerais",
  "Entertainment: Books": "Entretenimento: Livros",
  "Entertainment: Film": "Entretenimento: Filmes",
  "Entertainment: Music": "Entretenimento: Música",
  "Entertainment: Musicals & Theatres": "Entretenimento: Musicais e Teatro",
  "Entertainment: Television": "Entretenimento: Televisão",
  "Entertainment: Video Games": "Entretenimento: Videogames",
  "Entertainment: Board Games": "Entretenimento: Jogos de Tabuleiro",
  "Science & Nature": "Ciência e Natureza",
  "Science: Computers": "Ciência: Computadores",
  "Science: Mathematics": "Ciência: Matemática",
  "Mythology": "Mitologia",
  "Sports": "Esportes",
  "Geography": "Geografia",
  "History": "História",
  "Politics": "Política",
  "Art": "Arte",
  "Celebrities": "Celebridades",
  "Animals": "Animais",
  "Vehicles": "Veículos",
  "Entertainment: Comics": "Entretenimento: Quadrinhos",
  "Science: Gadgets": "Ciência: Gadgets",
  "Entertainment: Japanese Anime & Manga": "Entretenimento: Anime e Mangá",
  "Entertainment: Cartoon & Animations": "Entretenimento: Desenhos e Animações",
};